config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  root 'welcome#index'
  namespace :admin do
    resources :poorfarmers
    resources :effects
    resources :aids
    resources :funds
    resources :judgments
    resources :policies
    resources :categories
    resources :villages
  end
  resources :poorfarmers
  resources :effects
  resources :aids
  resources :funds
  resources :judgments
  resources :policies
  resources :villages
end

app/models/aid.rb
class Aid < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :poorfarmers
end

app/models/effect.rb
class Effect < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/fund.rb
class Fund < ApplicationRecord
end

app/models/judgment.rb
class Judgment < ApplicationRecord
end

app/models/policy.rb
class Policy < ApplicationRecord
end

app/models/poorfarmer.rb
class Poorfarmer < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/village.rb
class Village < ApplicationRecord
end

app/controllers/admin/judgments_controller.rb
class Admin::JudgmentsController < ApplicationController
  layout "admin"
  before_action :authenticate_user!

  def index
    @judgments = Judgment.all.page(params[:page]).per(15)
  end

  def new
    @judgment = Judgment.new
  end

  def edit
    @judgment = Judgment.find(params[:id])
  end

  def update
    @judgment = Judgment.find(params[:id])

    if @judgment.update(judgment_params)
      redirect_to admin_judgments_path
    else
      render :edit
    end
  end

  def create
    @judgment = Judgment.new(judgment_params)

    if @judgment.save
      redirect_to admin_judgments_path
    else
      render :new
    end
  end

  def destroy
    @judgment = Judgment.find(params[:id])
    @judgment.destroy
    redirect_to admin_judgments_path
  end

  private

  def judgment_params
    params.require(:judgment).permit(:title, :description, :image)
  end
end

app/controllers/aids_controller.rb
class AidsController < ApplicationController
  def index
    @aids = Aid.all.page(params[:page]).per(15)
  end

  def show
    @aid = Aid.find(params[:id])
  end
end

app/controllers/effects_controller.rb
class EffectsController < ApplicationController
  def index
    @effects = Effect.all.page(params[:page]).per(15)
  end

  def show
    @effect = Effect.find(params[:id])
  end
end

app/controllers/funds_controller.rb
class FundsController < ApplicationController
  def index
    @funds = Fund.all.page(params[:page]).per(15)
  end

  def show
    @fund = Fund.find(params[:id])
  end
end

app/controllers/judgments_controller.rb
class JudgmentsController < ApplicationController
  def index
    @judgments = Judgment.all.page(params[:page]).per(15)
  end

  def show
    @judgment = Judgment.find(params[:id])
  end
end

app/helpers/admin/judgments_helper.rb
module Admin::JudgmentsHelper
end

app/helpers/aids_helper.rb
module AidsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/effects_helper.rb
module EffectsHelper
end

app/helpers/funds_helper.rb
module FundsHelper
end

app/helpers/judgments_helper.rb
module JudgmentsHelper
end

app/helpers/policies_helper.rb
module PoliciesHelper
end

app/helpers/poorfarmers_helper.rb
module PoorfarmersHelper
end

app/helpers/villages_helper.rb
module VillagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/judgments/_form.html.erb
<%= simple_form_for [:admin, @judgment] do |f| %>

  <div class="group">
    <%= f.input :title, :label => "识别名称" %>
  </div>

  <% if @judgment.image.present? %>
   <span>目前图片</span>

   <%= image_tag(@judgment.image.thumb.url) %>
  <% end %>

  <div class="group">
    <%= f.input :image, as: :file %>
  </div>

  <div class="group">
    <%= f.input :description, as: :ckeditor, input_html: { ckeditor: { toolbar: 'mini' } }, :label => "内容" %>
  </div>


  <%= f.submit "Submit", data: { disable_with: "Submitting..." } %>

<% end %>

app/views/admin/judgments/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10">
      <h2 class="text-center">编辑识别</h2>
      <hr>
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/admin/judgments/index.html.erb
<div class="container">
  <div class="row">
    <br><br><br>
    <div class="col-md-10 text-center">
      <h3> 识别情况 </h3>
    </div>
    <div class="col-md-10">
      <div class="pull-right" style="padding-bottom: 20px;">
        <%= link_to("新增识别", new_admin_judgment_path, class: "btn btn-info btn-sm") %>
      </div>
      <table class="table table-hover  table-responsive">
        <thead class="text-center">
          <tr>
            <th>序号</th>
            <th>识别名称</th>
            <th width="100">操作选项</th>
          </tr>
        </thead>
        <tbody>
          <% @judgments.each do |judgment| %>
            <tr>
              <td>
                <%= judgment.id %>
              </td>
              <td>
                <%= judgment.title %>
              </td>
              <td>
                <%= link_to("编辑", edit_admin_judgment_path(judgment)) %> |
                <%= link_to("删除", admin_judgment_path(judgment), :method => :delete, :data => { :confirm => "Are you sure?"}) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @judgments %>
    </div>
  </div>
</div>

app/views/admin/judgments/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10">
      <h2 class="text-center">新增识别</h2>
      <hr>
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/judgments/index.html.erb
<br><br><br>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h3 class="text-center">精准识别</h3>
    </div>
    <br><br><br>
<div class="col-md-10">
    <table class="table table-hover table-responsive">
      <tbody>
        <% @judgments.each do |judgment| %>
          <tr>
            <td>
              <%= judgment.id %>
            </td>
            <td>
              <%= link_to(judgment.title, judgment_path(judgment)) %>
            </td>

          </tr>
        <% end %>
      </tbody>
    </table>
</div>
  </div>
</div>
<div class="text-center">
  <%= paginate @judgments %>
</div>

app/views/judgments/show.html.erb
<br><br><br>
<div class="container">
  <div class="row">

    <div class="col-md-12 text-center">
      <h2> <%= @judgment.title %> </h2>
      <div>
        <p>
          <%== @judgment.description %>
        </p>
      </div>
    </div>
  </div>
</div>