config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  root 'welcome#index'
  namespace :admin do
    resources :poorfarmers
    resources :effects
    resources :aids
    resources :funds
    resources :judgments
    resources :policies
    resources :categories
    resources :villages
  end
  resources :poorfarmers
  resources :effects
  resources :aids
  resources :funds
  resources :judgments
  resources :policies
  resources :villages
end

app/models/aid.rb
class Aid < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :poorfarmers
end

app/models/effect.rb
class Effect < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/fund.rb
class Fund < ApplicationRecord
end

app/models/judgment.rb
class Judgment < ApplicationRecord
end

app/models/policy.rb
class Policy < ApplicationRecord
end

app/models/poorfarmer.rb
class Poorfarmer < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/village.rb
class Village < ApplicationRecord
end

app/controllers/admin/poorfarmers_controller.rb
class Admin::PoorfarmersController < ApplicationController
  layout "admin"
  before_action :authenticate_user!

  def index
    @poorfarmers = Poorfarmer.all.page(params[:page]).per(15)
    @current_page = @poorfarmers.current_page

  end

  def new
    @poorfarmer = Poorfarmer.new
    @categories = Category.all.map { |c| [c.name, c.id]}
  end

  def edit
    @poorfarmer = Poorfarmer.find(params[:id])
    @categories = Category.all.map { |c| [c.name, c.id] }
  end



  def update
    @poorfarmer = Poorfarmer.find(params[:id])
    @poorfarmer.category_id = params[:category_id]

    if @poorfarmer.update(poorfarmer_params)
      redirect_to admin_poorfarmers_path
    else
      render :edit
    end
  end

  def create
    @poorfarmer = Poorfarmer.new(poorfarmer_params)
    @poorfarmer.category_id = params[:category_id]

    if @poorfarmer.save
      redirect_to admin_poorfarmers_path
    else
      render :new
    end
  end

  def destroy
    @poorfarmer = Poorfarmer.find(params[:id])
    @poorfarmer.destroy
    redirect_to admin_poorfarmers_path
  end


  private

  def poorfarmer_params
    params.require(:poorfarmer).permit(:title, :description, :quantity, :image, :helper, :category, :category_id)
  end
end

app/controllers/aids_controller.rb
class AidsController < ApplicationController
  def index
    @aids = Aid.all.page(params[:page]).per(15)
  end

  def show
    @aid = Aid.find(params[:id])
  end
end

app/controllers/effects_controller.rb
class EffectsController < ApplicationController
  def index
    @effects = Effect.all.page(params[:page]).per(15)
  end

  def show
    @effect = Effect.find(params[:id])
  end
end

app/controllers/funds_controller.rb
class FundsController < ApplicationController
  def index
    @funds = Fund.all.page(params[:page]).per(15)
  end

  def show
    @fund = Fund.find(params[:id])
  end
end

app/controllers/poorfarmers_controller.rb
class PoorfarmersController < ApplicationController
  def index
    # @poorfarmers = Poorfarmer.all.page(params[:page]).per(15)

    if params[:category].blank?
      @poorfarmers = Poorfarmer.all.page(params[:page]).per(8)
    else
      @category_id = Category.find_by(name: params[:category]).id
      @poorfarmers = Poorfarmer.where(:category_id => @category_id).page(params[:page]).per(8)
    end
  end

  def show
    @poorfarmer = Poorfarmer.find(params[:id])
  end
end

app/helpers/admin/poorfarmers_helper.rb
module Admin::PoorfarmersHelper
end

app/helpers/aids_helper.rb
module AidsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/effects_helper.rb
module EffectsHelper
end

app/helpers/funds_helper.rb
module FundsHelper
end

app/helpers/judgments_helper.rb
module JudgmentsHelper
end

app/helpers/policies_helper.rb
module PoliciesHelper
end

app/helpers/poorfarmers_helper.rb
module PoorfarmersHelper
end

app/helpers/villages_helper.rb
module VillagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/poorfarmers/_form.html.erb
<%= simple_form_for [:admin, @poorfarmer] do |f| %>

  <div class="group">
    <%= f.input :title, :label => "户主" %>
  </div>

  <% if @poorfarmer.image.present? %>
   <span>目前图片</span>

   <%= image_tag(@poorfarmer.image.thumb.url) %>
  <% end %>

  <div class="group">
    <%= f.input :image, as: :file %>
  </div>

  <div class="group">
    <%= f.input :description, as: :ckeditor, input_html: { ckeditor: { toolbar: 'mini' } }, :label => "内容" %>
  </div>

  <% if @poorfarmer.category_id.present? %>
   <span>目前分类：</span>
   <%= @poorfarmer.category.try(:name) %>
  <% end %>
  
  <div class="group">
    <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Category") %>
  </div>

  <div class="group">
    <%= f.input :quantity, :label => "家庭人口" %>
  </div>

  <div class="group">
    <%= f.input :helper, :label => "帮扶责任人" %>
  </div>

  <%= f.submit "Submit", data: { disable_with: "Submitting..." } %>

<% end %>

app/views/admin/poorfarmers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10">
      <h2 class="text-center">编辑贫困户</h2>
      <hr>
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/admin/poorfarmers/index.html.erb
<link rel="stylesheet" href="bootstrap-table.css">

<div class="container">
  <div class="row">
    <br><br><br>
    <div class="col-md-10 text-center">
      <h3> 贫困户列表 </h3>
    </div>
    <div class="col-md-10">
      <div class="pull-right" style="padding-bottom: 20px;">
        <%= link_to("新增贫困户", new_admin_poorfarmer_path, class: "btn btn-info btn-sm") %>
      </div>
      <table data-toggle="table" class="table table-hover  table-responsive">
        <thead class="text-center">
          <tr>

            <th>序号</th>
            <th width="220">照片</th>
            <th>贫困户属性</th>
            <th>户主</th>
            <th>家庭人数</th>
            <th>帮扶责任人</th>
            <th width="100">操作选项</th>
          </tr>
        </thead>
        <tbody>
          <% @poorfarmers.each_with_index do |poorfarmer, index| %>
            <tr>
              <td>
                <%= (@current_page-1)*15+index+1 %>
              </td>
              <td>
                <%= link_to poorfarmer_path(poorfarmer) do %>
                  <% if poorfarmer.image.present? %>
                    <%= image_tag(poorfarmer.image.thumb.url, class: "thumbnail") %>
                  <% else %>
                    <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
                  <% end %>
                <% end %>
              </td>
              <td>
                <%= poorfarmer.category.try(:name) %>
              </td>
              <td>
                <%= poorfarmer.title %>
              </td>
              <td>
                <%= poorfarmer.quantity %>
              </td>
              <td>
                <%= poorfarmer.helper %>
              </td>
              <td>
                <%= link_to("编辑", edit_admin_poorfarmer_path(poorfarmer)) %> |
                <%= link_to("删除", admin_poorfarmer_path(poorfarmer), :method => :delete, :data => { :confirm => "Are you sure?"}) %>
              </td>
            </tr>
          <% end %>
        </tbody>


      </table>
      <%= paginate @poorfarmers %>
    </div>
  </div>
</div>

app/views/admin/poorfarmers/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10">
      <h2 class="text-center">新增贫困户</h2>
      <hr>
      <%= render "form" %>
    </div>
  </div>
</div>