config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  root 'welcome#index'
  namespace :admin do
    resources :poorfarmers
    resources :effects
    resources :aids
    resources :funds
    resources :judgments
    resources :policies
    resources :categories
    resources :villages
  end
  resources :poorfarmers
  resources :effects
  resources :aids
  resources :funds
  resources :judgments
  resources :policies
  resources :villages
end

app/models/aid.rb
class Aid < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :poorfarmers
end

app/models/effect.rb
class Effect < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/fund.rb
class Fund < ApplicationRecord
end

app/models/judgment.rb
class Judgment < ApplicationRecord
end

app/models/policy.rb
class Policy < ApplicationRecord
end

app/models/poorfarmer.rb
class Poorfarmer < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/village.rb
class Village < ApplicationRecord
end

app/controllers/aids_controller.rb
class AidsController < ApplicationController
  def index
    @aids = Aid.all.page(params[:page]).per(15)
  end

  def show
    @aid = Aid.find(params[:id])
  end
end

app/helpers/aids_helper.rb
module AidsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/effects_helper.rb
module EffectsHelper
end

app/helpers/funds_helper.rb
module FundsHelper
end

app/helpers/judgments_helper.rb
module JudgmentsHelper
end

app/helpers/policies_helper.rb
module PoliciesHelper
end

app/helpers/poorfarmers_helper.rb
module PoorfarmersHelper
end

app/helpers/villages_helper.rb
module VillagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_footer.html.erb
<footer class="footer">
  <div class="container">

      <hr>
    <div class="row">

      <div class="col-xs-4 col-sm-4 col-md-4 text-left">
        <a href="https://210.76.68.130:8443/cas/login?service=http://210.76.68.61:80/fpy/a/login" >链接：广东扶贫云</a>
      </div>
      <div class="col-xs-4 col-sm-4 col-md-4 text-center">
        <p>帮扶单位：龙岗区坂田街道办、科技创新局、汕尾市科协</p>
      </div>
      <div class="col-xs-4 col-sm-4 col-md-4 text-right">
        <p>制作：下埔驻村工作队</p>
      </div>
    </div>
  </div>
</footer>

app/views/common/_navbar.html.erb
<!-- <nav class="navbar navbar-default navbar-fixed-top navbar-style" role="navigation">
  <div class="container">
    <div class="navbar-header nav-container">
      <a  href="/" class="navbar-brand ">下埔村精准扶贫精准脱工作网</a>
    </div>

    <div class="navbar-collapse navbar-ex1-collapse collapse " aria-expanded="false">
      <ul class="nav navbar-nav">

        <li>
          <%= link_to("贫困户", poorfarmers_path) %>
        </li>
        <li>
          <%= link_to("减贫成效", ) %>
        </li>
        <li>
          <%= link_to("精准帮扶", ) %>
        </li>
        <li>
          <%= link_to("扶贫资金", ) %>
        </li>
        <li>
          <%= link_to("精准识别", ) %>
        </li>
        <li>
          <%= link_to("文件政策", ) %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>

          <li><%= link_to("注册", new_user_registration_path) %></li>
          <li><%= link_to(content_tag(:i, "登录", class: "fa fa-sign-in"), new_user_session_path) %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Hi!, <%= current_user.email %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to("管理后台", admin_poorfarmers_path) %></li>
              <li><%= link_to(content_tag(:i, "退出", class: "fa fa-sign-out"), destroy_user_session_path, method: :delete) %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav> -->


<nav class="navbar navbar-default navbar-fixed-top navbar-style" role="navigation">
  <div class="container">
      <div class="navbar-header nav-container">
        <a  href="/" class="navbar-brand "><img src='<%= image_url 'logo.png' %> '>下埔村精准扶贫精准脱贫工作网</a>
      </div>

    <!-- 菜单 -->
    <div class="navbar-collapse navbar-ex1-collapse collapse " aria-expanded="false">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to("新农村", villages_path) %>
        </li>
        <li>
          <%= link_to("贫困户", poorfarmers_path) %>
        </li>
        <li>
          <%= link_to("减贫成效", effects_path) %>
        </li>
        <li>
          <%= link_to("精准帮扶", aids_path) %>
        </li>
        <li>
          <%= link_to("扶贫资金", funds_path) %>
        </li>
        <li>
          <%= link_to("精准识别", judgments_path) %>
        </li>
        <li>
          <%= link_to("文件政策", policies_path) %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
          <li><%= link_to("注册", new_user_registration_path) %></li>
          <li><%= link_to(content_tag(:i, "登录", class: "fa fa-sign-in"), new_user_session_path) %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.email %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to("管理后台", admin_poorfarmers_path) %></li>
              <li><%= link_to(content_tag(:i, "退出", class: "fa fa-sign-out"), destroy_user_session_path, method: :delete) %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
    </div>
</nav>